apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techsolutions-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /tech/?(.*)
        pathType: Prefix
        backend:
          service:
            name: techsolutions-service
            port:
              number: 80
